### ISSUE TITLE
CocAction('format') formats with tab incorrectly.

### ISSUE THREAD

**Issue by Avi-D-coder** [neoclide/coc-rls#14]
`cargo fmt` correctly uses spaces (the rustfmt default), but Coc format is using tabs. I don't have a `rustfmt.toml` so it should be using the default setting.

**Comment by chemzqm** [comment]
Could you provide your format options, like `'expandtab'` `'shiftwidth'` and `'tabstop'`?

**Comment by Avi-D-coder** [comment]
All are set to 4.
I use https://github.com/tpope/vim-sleuth

**Comment by Avi-D-coder** [comment]
This gets even weirder. There is no plugin conflict, no `rustfmt.toml` in a parent directories.
When this `rustfmt.toml` is present Coc adds the option [`indent_style = "Visual"`](https://github.com/rust-lang/rustfmt/blob/master/Configurations.md#visual).

rustfmt.toml
```toml
hard_tabs = false
```

minirc.vim
```vim
call plug#begin()
Plug 'neoclide/coc.nvim', {'do': 'yarn install'}
call plug#end()
```
`:call CocAction('format')`
```rust
mod rope_diff;

use std::env;
use std::process::Command;

fn main() {
        Command::new(
                env::args()
                        .nth(1)
                        .expect("Provide lsp command as first argument."), 
        )
        .args(env::args().skip(2));
}
```

rustfmt
```rust
mod rope_diff;

use std::env;
use std::process::Command;

fn main() {
    Command::new(
        env::args()
            .nth(1)
            .expect("Provide lsp command as first argument."),
    )
    .args(env::args().skip(2));
}
```

**Comment by Avi-D-coder** [comment]
`rg -H --type=toml 'indent_style'` on root returns nothing.
`rg -H --type=toml 'hard_tabs'` returns only the aforementioned `rustfmt.toml`.

**Comment by chemzqm** [comment]
Need verbose output from language server https://github.com/neoclide/coc.nvim/wiki/Debug-language-server#using-output-channel to know what happened.

**Comment by chemzqm** [comment]
Should be fixed on master of coc.nvim.

**Comment by Avi-D-coder** [comment]
Thanks
