### ISSUE TITLE
Problem with installation 

### ISSUE THREAD

**Issue by splitcircle** [neoclide/coc-rls#19]
after following installation instructions, I open a rust file as instructed. I get prompted with the message "RLS not installed. Install?" and I select Yes. However, upon doing so I get this error:
![Screen Shot 2019-04-27 at 8 26 31 AM](https://user-images.githubusercontent.com/15125965/56849766-d2258b80-68c6-11e9-9c75-aa9e5ac86861.png)

also, the output from `:CocInfo`:

```## versions

vim version: NVIM v0.3.0
node version: v10.10.0
coc.nvim version: 0.0.65
term: iTerm.app
platform: darwin

## Error messages

## Output channel: snippets

## Output channel: rust-client
[Error  - 8:31:29 AM] Starting client failed: 
Error: Error starting up rls.
```

**Comment by chemzqm** [comment]
Installation can fail for many reasons, checkout rls documentation https://github.com/rust-lang/rls for setup rls on your system.

**Comment by chemzqm** [comment]
Got the problem, coc-rls install rls-proview which should be rls.
