### ISSUE TITLE
rust-client fails with internal compiler error

### ISSUE THREAD

**Issue by fungl164** [neoclide/coc-rls#21]
## command
running ```:RustRun``` with the rust example from the website yields this error.  However, running ```cargo run``` from command-line works fine.

Cargo.toml
```toml
[package]
name = "hello"
version = "0.1.0"
authors = ["luis"]
edition = "2018"

[dependencies]
ferris-says = "0.1"
```
main.rs
```rust
use ferris_says::say; // from the previous step
use std::io::{stdout, BufWriter};

fn main() {
    let stdout = stdout();
    let out = b"Hello fellow Rustaceans!";
    let width = 24;

    let mut writer = BufWriter::new(stdout.lock());
    say(out, width, &mut writer).unwrap();
}
```

## versions

vim version: NVIM v0.3.4
node version: v12.1.0
coc.nvim version: 0.0.66
cargo 1.34.0 (6789d8a0a 2019-04-01)
rustc 1.34.1 (fc50f328b 2019-04-24)
term: xterm-256color
platform: linux

## Error messages
error[E0432]: unresolved import "ferris_says"

## Output channel: rust-client

{"message":"src/librustc/ty/context.rs:541: node_type: no type for node `expr <Self>::SC_NEGATE_REQS (id=50338)`","code":null,"level":"error: internal compiler error","spans":[],"children":[],"rendered":"error: internal compiler error: src/librustc/ty/context.rs:541: node_type: no type for node `expr <Self>::SC_NEGATE_REQS (id=50338)`\n\n"}
thread 'rustc
' panicked at 'Box<Any>', src/librustc_errors/lib.rs:620:9
note: Run with `RUST_BACKTRACE=1` environment variable to display a backtrace.
{"message":"aborting due to previous error","code":null,"level":"error","spans":[],"children":[],"rendered":"error: aborting due to previous error\n\n"}

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/blob/master/CONTRIBUTING.md#bug-reports

note: rustc 1.34.1 (fc50f328b 2019-04-24) running on x86_64-unknown-linux-gnu

note: compiler flags: -C debuginfo=2 --crate-type lib

note: some of the compiler flags provided by cargo are hidden

**Comment by fungl164** [comment]
FYI, 
- PlugUpdated coc.nvim
- uninstalled/re-installed coc-rls 
- Nightly and stable both fail

## versions

vim version: NVIM v0.3.4
node version: v12.1.0
coc.nvim version: 0.0.67-8741e930c9
term: xterm-256color
platform: linux

## Error messages
Same error [E0432]

## Output channel: rust-client

{"message":"src/librustc/ty/context.rs:565: node_type: no type for node `expr <Self>::SC_NEGATE_REQS (hir_id=HirId { owner: DefIndex(0:1500), local_id: 4 })`","code":null,"level":"error: internal compiler error","spans":[],"children":[],"rendered":"error: internal compiler error: src/librustc/ty/context.rs:565: node_type: no type for node `expr <Self>::SC_NEGATE_REQS (hir_id=HirId { owner: DefIndex(0:1500), local_id: 4 })`\n\n"}
thread 'rustc' panicked at 'Box<Any>', 
src/librustc_errors/lib.rs:643:9
note: Run with `RUST_BACKTRACE=1` environment variable to display a backtrace.
{"message":"aborting due to previous error","code":null,"level":"error","spans":[],"children":[],"rendered":"error: aborting due to previous error\n\n"}

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/blob/master/CONTRIBUTING.md#bug-reports

note: rustc 1.36.0-nightly (a19cf18c7 2019-05-06) running on x86_64-unknown-linux-gnu

note: compiler flags: -C debuginfo=2 --crate-type lib

note: some of the compiler flags provided by cargo are hidden

**Comment by chemzqm** [comment]
You should report issue at https://github.com/rust-lang/rust/blob/master/CONTRIBUTING.md#bug-reports.

**Comment by fungl164** [comment]
@chemzqm thanks for responding quickly.  I appreciate the help.  I can open up an issue at rust-lang, but what exactly do I tell them?  I don't know enough about what ```coc-rls``` is doing in the background that is different from just running ```cargo run```.  

Would you mind explaining a little about what is happening in the background so anyone else reading can understand the interaction between```coc-rls``` and ```rustc```/```cargo```? Many thnxs!
