### ISSUE TITLE
Disabling startup logs.

### ISSUE THREAD

**Issue by peitalin** [neoclide/coc-rls#24]
Hi, thanks for making this library.
Just a question. How do you disable [coc.nvim] startup messages?
I keep getting these two messages (which only recently appeared) and am unsure which settings can disable it:
![image](https://user-images.githubusercontent.com/4037878/58564879-211d6280-8271-11e9-85e9-5b5851164da8.png)
![image](https://user-images.githubusercontent.com/4037878/58564907-2d092480-8271-11e9-882c-80d035aeb125.png)

I have tried `"diagnostic.level": false` in the CocConfigs with no effect.

**Comment by chemzqm** [comment]
Avoid use rust up to disable it

**Comment by peitalin** [comment]
Thanks, do you mean these settings?
![image](https://user-images.githubusercontent.com/4037878/58597637-366bae80-82bc-11e9-8ca5-e6a653bbd627.png)

It doesn't appear to disable these messages?

**Comment by chemzqm** [comment]
They're important messages, you can use `set cmdheight=2` to avoid `Press Enter` or remove those messages by change the code and compile yourself.

**Comment by peitalin** [comment]
Ok thanks, I re-installed neovim and the messages went away. Thanks for your help.
