### ISSUE TITLE
do not require rustup

### ISSUE THREAD

**Issue by lilydjwg** [neoclide/coc-rls#25]
I don't use rustup because I don't want another package manager. I just `pacman -S rust` and rls and analysis and src are available. But coc-rls doesn't work :-(

**Comment by chemzqm** [comment]
Use rust-client.disableRustup setting.

**Comment by lilydjwg** [comment]
Thanks!

**Comment by lilydjwg** [comment]
Btw, can you update the docs saying that rustup is optional?
