### ISSUE TITLE
Completing entire function signature?

### ISSUE THREAD

**Issue by mankinskin** [neoclide/coc-rls#27]
Hi, i am using neoclide/coc.nvim and [autozimu/LanguageClient-neovim](https://github.com/autozimu/LanguageClient-neovim) in neovim for syntax completion in rust. It works great, as soon as I download a new crate, the language server finds it (I did `:CocInstall coc-rls`) and shows function signature, trait definition, everything. 

But I was wondering if I could configure these plugins to provide the entire function signature as completion, i.e. if I bring up the completion menu with tab (I use [ervandew/supertab](https://github.com/ervandew/supertab)) it will insert the entire signature of the function I selected. Is this something I could do using this plugin?

**Comment by chemzqm** [comment]
Completion for function signature as snippets just work on confirm completion with coc.nvim.
https://github.com/neoclide/coc.nvim/wiki/Using-snippets
