### ISSUE TITLE
Proposal: use Trusty Rusty Snippets for more comprehensive snippets

### ISSUE THREAD

**Issue by kevinkassimo** [neoclide/coc-rls#28]
https://github.com/polypus74/trusty_rusty_snippets
This is recommended in the README of https://github.com/rust-lang/rls-vscode
The default set from rls-vscode might be too conservative for practical use.

**Comment by chemzqm** [comment]
You can install it by `:CocInstall https://github.com/polypus74/trusty_rusty_snippets`
Like rls-vscode, we won't include them in coc-rls.
