### ISSUE TITLE
Running :Coclist diagnostics fails

### ISSUE THREAD

**Issue by curtis0x** [neoclide/coc-rls#29]
When I try to run the rls diagnostics using `:Coclist diagnostics`, I get the following error in the logs:

`'Vim:E117: Unknown function: coc#util#set_buf_var'`

Here are the top level versions:
vim version: NVIM v0.3.7
node version: v10.13.0
coc.nvim version: 0.0.72-89a83c1d29
term: xterm-256color
platform: linux

**Comment by chemzqm** [comment]
Please use `Plug 'neoclide/coc.nvim', {'branch': 'release'}` to install coc.nvim.
