### ISSUE TITLE
:CocRestart required?

### ISSUE THREAD

**Issue by cdebotton** [neoclide/coc-rls#30]
Sorry if this has been asked before, I couldn't find any related issues. I'm using the latest `coc.nvim` and stable `coc-rls`, Code completions and suggestions are working, but I don't seem to see updated errors or warnings without invoking `:CocRestart`. Is this the expected behavior?

Additional info:
nvim 0.3.8
macos

**Comment by chemzqm** [comment]
If you added new module to cargo.toml, you have to use `:CocRestart` for rls work as expected, it's limitation of rls.

**Comment by cdebotton** [comment]
@chemzqm Thanks for the quick reply! This is actually not an issue of adding modules to `cargo.toml`. I'm opening a new project created with `cargo new` and typing:

```rust
fn test() {
    let test_var: u8 = "this is a &str";  
}
```

And no errors. Running `:CocRestart` surfaces the expected mismatched type error.

Changing this to:
```rust
fn test() {
    let test_var: u8 = 6;
}
```

Doesn't change any of the error/warning output again until I run `:CocRestart`, at which point I see the unused variable warning.

**Comment by chemzqm** [comment]
Should be problem of rls analyzing your project, checkout `:h coc-status` for status line integration.

**Comment by cdebotton** [comment]
@chemzqm Sorry I should clarify, without invoking `:CocRestart`, it doesn't seem as though vim is aware of errors at all. They aren't in the status line, but also, the error and warning indicators in the gutter don't become visible until running that command.

I also just realized I'm encountering the same issue with `coc-tsserver`

**Comment by chemzqm** [comment]
Can't reproduce, can you check if `:CocList diagnostics` have errors?

**Comment by cdebotton** [comment]
@chemzqm I was very wrong! The correct diagnostics are displayed there.

**Comment by cdebotton** [comment]
I can't find any info that would show why the errors don't surface in my left gutter until I invoke `:CocRestart` though.

**Comment by chemzqm** [comment]
Maybe it's cleared by some of your other vim plugin, try minimal vimrc.
