### ISSUE TITLE
Code: -32603 

### ISSUE THREAD

**Issue by mredaelli** [neoclide/coc-rls#31]
When I save a Rust file I often get this error message: 'Code: -32603'

Could it be `rustfmt`? The buffer doesn't change in vim, but when I run it from the command line I get no problems and the file is formatted.

**Comment by chemzqm** [comment]
Its internal error from RLS, I don't have this issue, you need ask at https://github.com/rust-lang/rls

**Comment by mredaelli** [comment]
OK, thanks
