### ISSUE TITLE
Nixos documentation

### ISSUE THREAD

**Issue by mredaelli** [neoclide/coc-rls#32]
I have successfully installed the plugin in my Nixos system, and I was wondering why the documentation suggests to install and use rustup. (Disclaimer: very new to this.)

When using the Mozilla overlay, correct me if I'm wrong, you already get a channel. Then you fire up vim and coc, and it uses rustup to download and install another stable (or whatever) channel.

Instead I simply put ` "rust-client.disableRustup": true` in the config, no rustup in `default.nix`, and it seems to work.

Am I missing something?

**Comment by chemzqm** [comment]
It's just same behavior of https://github.com/rust-lang/rls-vscode

**Comment by chemzqm** [comment]
The doc at https://github.com/neoclide/coc-rls#nixos seems need some fix, but I don't know how, consider help by send PR.
