### ISSUE TITLE
CocAction("format") looses information when sorting `use` statements.

### ISSUE THREAD

**Issue by iago-lito** [neoclide/coc-rls#33]
With this simple `main.rs`:
```rust
use b;
use a;
use c;

fn main() {}
```

`:call CocAction("format")` transforms the file to:

```rust

use a;
use b;

fn main() {}
```
.. which is *very wrong*, as I expect

```rust
use a;
use b;
use c;

fn main() {}
```

so I've just.. lost information :\\

What could be wrong?

---

Clue 1:

The problem also occurs with vanilla `vim -u .vimrc-plain src/main.rs` with `.vimrc-plain`:

```vim
call plug#begin('~/.vim/plugged')

Plug 'neoclide/coc.nvim', {'branch': 'release'}

call plug#end()
```
Clue 2:

From a neighbouring shell, `cargo fmt` or `rustfmt src/main.rs` yields expected results. How do Coc and rustfmt interact?

**Comment by iago-lito** [comment]
The problem also occurs with VSCode, I'm thus moving the issue to [`rls`](https://github.com/rust-lang/rls/issues/1530).

**Comment by norru** [comment]
Please see https://github.com/rust-lang/rls/issues/1443#issuecomment-493507406
