### ISSUE TITLE
Does not format if there are errors

### ISSUE THREAD

**Issue by johnpyp** [neoclide/coc-rls#35]
Unlike other coc language servers, it seems like coc-rls won't run `rustfmt` unless there are no errors present in your project, even though `rustfmt` works on code that won't compile.

**Comment by chemzqm** [comment]
Should be issue of rls, you can checkout output channel.

**Comment by iago-lito** [comment]
My guess is that it actually depends on the error. When the syntax is so much broken than parsing the code is impossible, there is no way for `rustfmt` to run, for it does not even understand the tree structure of your file. However, if the errors are just semantic but the syntax is correct, then it does run fine.

**Comment by chemzqm** [comment]
Should be limitation of rustfmt.
