### ISSUE TITLE
Unknown RLS configuration: `use_crate_blacklist` on start w/ new RLS

### ISSUE THREAD

**Issue by billylindeman** [neoclide/coc-rls#36]
seems to be the same as this bug https://github.com/rust-lang/rls-vscode/issues/639

**Comment by chemzqm** [comment]
I think it should log to output channel, there could be people using old version of RLS.

**Comment by damienstanton** [comment]
Just want to point out that this is occurring on Rust stable (1.38) as of today, so it may be worth reopening and fixing.

**Comment by chemzqm** [comment]
rls should be compatible with old configuration instead of complain
