### ISSUE TITLE
rls-name now simply as rls in nightly

### ISSUE THREAD

**Issue by oblitum** [neoclide/coc-rls#4]
On my Rust installation now RLS is now simply named "rls", instead of "rls-preview". This cause coc-rls to fail a regex match because it defaults to match "rls-preview".

**Comment by oblitum** [comment]
It can be fixed setting `rust-client.rls-name`, but still, I'm leaving issue open because I'm not sure what should be the default, maybe both?

**Comment by chemzqm** [comment]
Checkout https://github.com/rust-lang/rls/issues/641

**Comment by oblitum** [comment]
@chemzqm not sure what's there to help. I have RLS, it's just named rls locally, not rls-preview anymore.

**Comment by chemzqm** [comment]
You can disable rust-client and use `rls` command to start server.

**Comment by oblitum** [comment]
Hi @chemzqm, it starts fine, I just need to set `rust-client.rls-name` to `rls` and all works. Another user that reported to have to set it here: https://github.com/neoclide/coc.nvim/issues/235.

I'm not sure whether the RLS devs flipped and changed names from `rls-preview` to just `rls` lately. Hence I've left the issue open as suggestion on that.

**Comment by chemzqm** [comment]
Checkout rls's documentation: https://github.com/rust-lang/rls#note-nightly-only

**Comment by oblitum** [comment]
*But it is included*, *I'm using it*, that's *not* the issue.... Anyway, closing.

**Comment by oblitum** [comment]
```
❯❯❯ rustup component add rls-preview rust-analysis rust-src
...
❯❯❯ rustup component list --toolchain nightly
cargo-x86_64-unknown-linux-gnu (default)
clippy-x86_64-unknown-linux-gnu
llvm-tools-preview-x86_64-unknown-linux-gnu
rls-x86_64-unknown-linux-gnu (installed)                   <<<<<<<< rls, not rls-preview as name anymore
rust-analysis-x86_64-unknown-linux-gnu (installed)
rust-docs-x86_64-unknown-linux-gnu (default)
rust-src (installed)
...
```

**Comment by oblitum** [comment]
This is the recent discussion where renaming of RLS component from "rls-preview" to "rls" is mentioned:

- https://internals.rust-lang.org/t/announcing-rust-2018-beta-release/8901

**Comment by oblitum** [comment]
It can already be installed with just rls:

```
rustup component add rls rust-analysis rust-src
```

The above works, which means "rls-preview" is being phased out. `rustup component add rls-preview rust-analysis rust-src` still works, but when installed [the component will be named simply "rls"](https://github.com/neoclide/coc-rls/issues/4#issuecomment-445120025).

**Comment by chemzqm** [comment]
It's fixed, just like rls-vscode did https://github.com/rust-lang/rls-vscode/commit/037807f0a8cc0bfeb41b95cc6072a5c7f29a57f2

**Comment by oblitum** [comment]
@chemzqm OK. Looks like I needed to remove `<project-dir>/target/rls/`  (or just the whole `<project-dir>/target/`) from project directory for coc stop offering installation of RLS when it was already installed in the system. The `<project-dir>/target/rls` had cached reference to the previous `rls-preview` component, and that made coc look up for `rls-preview` instead of `rls`. After deleting that folder, coc was able to pick `rls` by default now. So there's this problem with those project caches.
