### ISSUE TITLE
self is not expanded from snippets in trait implementations

### ISSUE THREAD

**Issue by Avishayy** [neoclide/coc-rls#40]
I am not sure whether I am misunderstanding something or my setup is buggy, here's a gif to demonstrate:
![](https://i.imgur.com/L0zHezz.gif)

Where does the issue originate from? I've tried searching online but it doesn't seem like anyone else is being affected by this.

**Comment by Avishayy** [comment]
Hm.. I guess that it thinks I am trying to use the function and not implement it for a trait, is there any way to make it aware of the current context?

**Comment by chemzqm** [comment]
This should be issue of your language server, can't help.
