### ISSUE TITLE
Unknown RLS configuration: `crate_blacklist` on opening any rust file

### ISSUE THREAD

**Issue by julian-g99** [neoclide/coc-rls#54]
Whenever I open a rust file, I get this error:
```[coc.nvim] Unknown RLS configuration: `crate_blacklist` ```
I've updated neovim itself and run `PlugUpdate` to make sure that things are updated. I know from #44 that this configuration option was recently name changed, but `crate_blacklist` is the new name.

**Comment by chemzqm** [comment]
It means your rls need upgrade.
