### ISSUE TITLE
Autosuggestion shows suggestions twice.

### ISSUE THREAD

**Issue by samyakb** [neoclide/coc-rls#58]
![screehot](https://i.postimg.cc/Hk7HQXfz/2020-03-02-213731-636x311-scrot.png)

Here coc shows two autosuggestion.

**Comment by chemzqm** [comment]
Remove rls configuration in your coc-settings.json if you're using coc-rls.

**Comment by samyakb** [comment]
Thank You. This fixed my issue I think we should update [Wiki](https://github.com/neoclide/coc.nvim/wiki/Language-servers#rust) to not add configuration settings for while using coc-rls

**Comment by samyakb** [comment]
I updated [Wiki](https://github.com/neoclide/coc.nvim/wiki/Language-servers#rust) stating below message

> For coc-rls do not add above configuration in coc-settings.json file just use ( rustup component add rls rust-analysis rust-src)
