### ISSUE TITLE
coc-implementation doesn't work

### ISSUE THREAD

**Issue by pronvis** [neoclide/coc-rls#60]
First of all, thanks for that plugin 👍 
Now, I am wondering why `coc-implementation` saying `Implementation not found` for `clone()` method in next code:
```
let opt: Option<i32> = Some(22);
opt.clone();
```

`coc-definition` jumps to `pub trait Clone`, thats seems legit. But I want to jump to `impl<T: Clone> Clone for Option<T>`, how to do that and why `coc-implementation` can't find it?

Looks like bug.

**Comment by chemzqm** [comment]
Should be problem of your language server, checkout https://github.com/neoclide/coc.nvim/wiki/Debug-language-server#using-output-channel

**Comment by T0maas** [comment]
I have same issue, with c++. 
I have this code:
main.cc
```
#include "test.h"
int main() {
    Testme();
    return  0;
}
```
test.h:
```
#pragma once
extern void Testme();
```
test.cc
```
#include "test.h"
#include <cstdio>
void Testme() {
    puts("test");
}
```
.ccls
```
g++
-I.

```
All files are in same folder. `coc-definition` and `coc-references` works as expected but `coc-implementation` shows _implementation not found_, when I put cursor to Testme() in main.cc and press `gi` (which is set as `nmap <silent> gi <Plug>(coc-implementation)`). 

My coc-settings.json contain this:
```
{
    "diagnostic.refreshOnInsertMode": true,
    "languageserver":{
        "ccls": {
            "command": "ccls",
            "filetypes": ["c","cc" ,"cpp", "objc", "objcpp"],
            "trace.server": "verbose",
            "initializationOptions": {
                "cacheDirectory": ".ccls-cache"
            }
        }
    }
}
```
