### ISSUE TITLE
Suppress startup message

### ISSUE THREAD

**Issue by dustypaws** [neoclide/coc-rls#62]
Is there a setting to suppress the follow message? Or is this unrelated to coc-rls?

![tempsnip](https://user-images.githubusercontent.com/19664015/81718072-9cc0f100-947b-11ea-8dc8-5cc5faf953dc.jpg)

**Comment by chemzqm** [comment]
No, it's important message and we don't have other way to display it, use `:set cmdheight=2` to avoid `Press ....`

You can hack https://github.com/neoclide/coc.nvim/blob/master/autoload/coc/util.vim#L373

**Comment by dustypaws** [comment]
I've removed all the superfluous messaging from the extension directly because I disagree with the notion of being forced to dismiss a notification that doesn't really benefit the development process. Vim is all about being unobtrusive and to the point, not about acknowledging something at startup that I'm already aware of.

**Comment by chemzqm** [comment]
>  I'm already aware of.

It's importance information and you may be not aware of.
