### ISSUE TITLE
Option to not to ask to install RLS?

### ISSUE THREAD

**Issue by pbzweihander** [neoclide/coc-rls#66]
It is very annoying that `RLS not installed. Install?` message is constantly popping up every time I open up the vim.
It will be nice to have an option like `"rust-client.ask_to_install_rls"` to disable the prompt.

**Comment by chemzqm** [comment]
But how could it work without rls?

**Comment by iago-lito** [comment]
I think they mean an option to say `yes` by default, is it what you meant @pbzweihander?

**Comment by pbzweihander** [comment]
No. I meant an option to say `no` by default. Check out my PR (#67)

I wanted to automatically disable coc-rls if RLS is not installed. This is useful when you override Rust version with `rustup override set`.

**Comment by vincentmader** [comment]
> But how could it work without rls?

Why should it not work without rls? Of course you can edit code without using a linter/checker...

The thing is, if you're running vim+coc on an Apple M1 chip (which I do), you're simply not able to install rls on the nightly rust build. If you try, you get an "error: component 'rls' for target 'aarch64-apple-darwin' is unavailable for download for channel 'nightly'". 

If you need to use the nightly build (which I do), then you'll have to manually say "no" **every single time** you start vim for rust development, which is super annoying, I've literally seen that prompt a dozen times only today. So until M1 + rust-nightly + coc-rls are compatible, I'd also strongly wish for an option like pbzweihander suggests.
