### ISSUE TITLE
Go to definition not working for rust stdlib

### ISSUE THREAD

**Issue by svalaskevicius** [neoclide/coc-rls#70]
Go to definition is working for external crates, but not rust sources.

I'm using nix based setup (on nixos), and have rust src included (which I can grep in terminal for what I need but quite time consuming).

**Comment by chemzqm** [comment]
You may need to configure something, but I don't know how.

**Comment by svalaskevicius** [comment]
apparently I was able to install rustup from nixpkgs, which updates all downloaded binaries with correct lib paths and it all works fine, for now :) 

would be good if this install path was mentioned in the README.md, as the current version leads to this issue.
