### ISSUE TITLE
Cant get autocompletion

### ISSUE THREAD

**Issue by raghavken** [neoclide/coc-rls#72]
Im using coc.nvim and installed coc-rls but Im not getting any autocompletion while editing rust files

**Comment by chemzqm** [comment]
Should be problem of your language server, checkout https://github.com/neoclide/coc.nvim/wiki/Debug-language-server#using-output-channel

**Comment by raghavken** [comment]
![image](https://user-images.githubusercontent.com/33642056/99866750-61fdeb00-2b79-11eb-85ed-9466e8cdd682.png)
 This is all thats in the logs.
