### ISSUE TITLE
Conflict with existing keybindings in init.vim

### ISSUE THREAD

**Issue by AlphabetsAlphabets** [neoclide/coc-rls#78]
`coc-rls` has a symbol search feature that is activated by pressing `<leader>s` however, I have a keybinding that opens the terminal with "s" as well the keybinding is `<leader>st`. I've tried to re-map the symbol search feature to another keybinding, but I can't find anything that's on the documentation.

**Comment by chemzqm** [comment]
It doesn't provide that key mapping.

**Comment by AlphabetsAlphabets** [comment]
> It doesn't provide that key mapping.

So then what does? CoC's base install?
