### ISSUE TITLE
Async and detect slow

### ISSUE THREAD

**Issue by hungpham3112** [neoclide/coc-rls#80]
Sometimes when I edit `Rust `file it reports a red message( It really good ) but after correct, it takes a while to index or detect so that really annoying and uncomfortable.

Can it be index fast like `clangd` ? I used and really love it.

![bandicam 2021-09-03 11-25-25-179](https://user-images.githubusercontent.com/75968004/131950445-d9aef041-e385-4307-a68c-ad329bc3ccae.gif)

**Comment by fannheyward** [comment]
The slow performance is caused by rls, the Rust language server, not coc-rls.
