### ISSUE TITLE
How to disable expandtab feature?

### ISSUE THREAD

**Issue by ProgrammingLife** [neoclide/coc-rls#84]
coc-rls enables it by default and overrides my ```noexpandtab``` option which set in ```.vimrc```.
I have:
```
	"rls.insertSpaces": false,
```
in my ```:CocConfig``` file.
After manually call the command:
```
:set noexpandtab
```
all works as expected. But I already have ```set noexpandtab``` setting in my ```~/.vimrc``` and it works fine for any other languages but not for Rust.

How to change this behaviour?

**Comment by chemzqm** [comment]
There's no such config `"rls.insertSpaces"`
`'expandtab'` option of buffer should be respected, check output of language server
