### ISSUE TITLE
How to turn off the linting?

### ISSUE THREAD

**Issue by ynotstartups** [neoclide/coc-rls#9]
Sorry to create an issue for asking this question, let me know if there are other ways for simple question like this.

**Comment by chemzqm** [comment]
There is `rust.show_warnings` setting.

**Comment by ynotstartups** [comment]
I set it to false, but I still see linting error like to following. 
<img width="651" alt="screenshot 2019-02-16 at 08 15 54" src="https://user-images.githubusercontent.com/13963732/52896693-27f0ff80-31c3-11e9-9c24-3b2a3ae4faea.png">

**Comment by chemzqm** [comment]
You can't turn off error, there is coc settings to turn off diagnostic display.

**Comment by ynotstartups** [comment]
Thank you for the rapid response! That’s exactly the setting I am looking for because I plan to use Ale for this kind of things!
